-- This test checks if the age of students is between 18 and 35. Is there a better way to write this test?
-- TODO: Uncomment the next line and write the test as an SQL query.
-- select 
--     ...
-- from ...
