-- This test checks if the gender of students is Male or Female. Is there a better way to write this test?
-- TODO: Uncomment the next line and write the test as an SQL query.
-- select 
--     ...
-- from ...
